# First age

## The Excision

[The Ghoul Knight](/cast/klaegcasleen_knights.qmd#the-ghoul-knight) forms the Excised realm

- The Lands were part of The Eminent Realm
- The Eminent Realm started an age long war with The Itinerant Realm
- The Itinerant Realm were a nomadic realm [The Moat Knight](/cast/other_holding_knights.qmd#the-moat-knight) and [The Shield Knight](/cast/other_holding_knights.qmd#the-shield-knight) come from.
- The Eminent Realm destroyed the Itinerant Realm
- However, this weakened the realm who were attacked by other realms.
- This caused the south part bordering the seas to become separated from the Eminent Realm. 
- [The Ghoul Knight](/cast/klaegcasleen_knights.qmd#the-ghoul-knight) along with other Knights took this opportunity to take over this part of the realm as their new realm, The Excised Realm.
- They could not do this alone and teamed up with the [Emerald Lights](/cast/the_emerald_lights.qmd) religion who had gathered support from the masses as a “peaceful” religious group who accepted refugees from The Itinerant Realm.
- As part of this partnership [The Ghoul Knight](/cast/klaegcasleen_knights.qmd#the-ghoul-knight) agreed that no Knights could hold a position of power in the church. Unfortunately for the church only Knights are allowed to hold positions of power in the seat of power.
- Over time all the other knights that followed [The Ghoul Knight](/cast/klaegcasleen_knights.qmd#the-ghoul-knight) from the Eminent Realm have been executed by him.