# Second age

Where our game starts.

## First Spring

- A new company of Knights enters the realm
    - Nettle The Story Knight
    - Sarover The Silk Knight
    - Deepwater The Violet Knight
    - Zephyr The Salt Knight

### The Terminator

Terminator: The moving line that divides the daylit and dark night os a planetary body.

- Civil war between the Emerald lights and the new sun religion breaks out at Fabriknock
    - The Sun religion wanted to feed the Green eyed Seer's skeleton to The Eagle
    - The reliquary was precious to the Emerald lights
    - The company of knights took it and offered it to the Steed of The green eyed seer
    - The seer revived and it and the tower assisted the Emerald lights in killing the eagle and its followers
    - Surviving sun worshippers were sent to be caretakers of [The Tangled Seer](/map/sanctums.qmd#s4)
    - The Company are heroes to the Emerald lights but have upset The Leaf Knight

<center>

**The Terminator**

Come one come all and here the tale of the terminator,<br>
the war betwixt sun and stars at Fabriknock.<br>
Arrived at the scene was a tower that was a levitator,<br>
Fore it had come to the forge rod to dock.

In chaos the devious suns stormed the keep of the curator,<br>
but our gallant knights' defence was as a rock.<br>
With reliquary in hand they became relocators,<br>
as they escaped in a manner of ad hoc.

Worry not they weren't no traitors,<br>
they revived our seer with eyes of hemlock.<br>
Lightning bolt, eagle boned crater,<br>
it's followers defeated and held in the stocks.

Now our seer will ascend and join the creators!<br>
But do not stay in remorseful shock.<br>
No, rejoice and become the celebrators!<br>
Join me all to look up and gawk.

</center>