---
title: "2024_03_11"
mainfont: Bitcount single
---

<center>

An eye in the sky,<br>can hear no lie.

</center>

A nice motto for the commencement of this new series of recordings.
There is much to see but watching is only so invigorating.
The other two claim this form of data capture us unnecessary but I am so fond of the various scripts I've read from this realm we monitor.

Why did I decide to start this now?
Why did I ask myself a question?
It's because I have started reading the the journal of a travelling researcher.
Her writing is very inspiring.
Unlike many of her fellow researchers she writes in a much more approachable style.
Its hard enough understanding these humans but then their writing is full of florality and jargon.
I am fascinated in their poetry but it makes it difficult to know what is fact or fiction.
Though they do seem to struggle with this themselves.
Her language is quite plain and to the point in comparison.
I aim to emulate it to a certain degree.

Of course simple prose would be very dull with interesting topics.
She seems quite bright and most importantly she has joined a company of knights.
That is, The Violet Knight's company.
It will be so illuminating to view what they did through the eyes of Axel.