# Inis Ocular

- Pronounced: Inn-ish Awk-you-lar
- Etymology: Inis is island in irish, ocular is related to eyes
- Location:
- Importance: Trade port for the realm to other realms across the sea. Trade only occurs here to quarantine merchants from other realms.

Inis Ocular is known for its observatory and has been taken over by the "Emerald lights” religion. They use the observatory to try to look out for the emerald lights in the sky. The leader is Mentha the Mint (they/them).

The official ruler, The Shield Knight, lives in a small garden house in the hallowed garden. Here, grows the alien flower, Trillium Blaschkanum (Blaschka known for the glass flowers). Each flower is spit into three from the stem to the head. Each third has one triangular petal and various triangular leaves. The thirds are connected by thin fibres. All of it looks quite glass-like and one third is coloured emerald, another third a dark iridescent, and the third a yellow colour. The leaves are fed to silk moth larvae producing green, black, or yellow silk depending on the leaves they eat. The silks possibly have other effects.

The Shield Knight is blackmailed by mehta the Mint to let the Emerald lights rule. This is because they have evidence of The Shield Knight skimming wealth off the top from the trade that passes through.

Additionally, there are a lot of leather workers as lots of leather is received from other realms through trade.

Used Prompts
Holding features Sage’s Den
Bailey includes Hallowed garden
Keep holds observatory
Food is wet pie
Goods are abundant leather
Luxuries are esoteric silk
Drama involves coup through blackmail
Woe is unseen fire
News of tournament mood content

