# The Cast

## Klaegcasleen (Kla-cleen)

- [The Ghoul Knight](/cast/klaegcasleen_knights.qmd#the-ghoul-knight) (he/him) 6-6
    - Head of seat of power 
    - Head of Repairers faction
- [The War Knight](/cast//klaegcasleen_knights.qmd#the-war-knight) (she/her) 1-6
    - Domain ruler
    - Leader of the reinforcement faction
- [The Fanged Knight](/cast/klaegcasleen_knights.qmd#the-fanged-knight) (he/him) 6-10
    - Steward
    - Repairer faction
- [The Horn Knight](/cast/klaegcasleen_knights.qmd#the-horn-knight) (she/her) 2-11
    - Marshal
    - Repairer faction
- [Lavandula the Lavender](/cast/the_emerald_lights.qmd) (she/her)
    - One of the three leaders of [The Emerald Lights](/cast/the_emerald_lights.qmd)

## Wanderers

- [The Mule Knight](/cast/wandering_knights.qmd#the-mule-knight) (they/them) 4-6
    - Sheriff of the realm
    - Helps both factions
- [The Bone Knight](/cast/wandering_knights.qmd#the-bone-knight) (she/her) 5-2
    - Envoy of the realm
    - Reinforcement faction

## Bochordil (Back-or-dill)

- [The Moat Knight](/cast/other_holding_knights.qmd#the-moat-knight) (they/them) 3-4
    - Ruler
- [The Rune Knight](/cast/other_holding_knights.qmd#the-rune-knight) (she/her) 4-1
    - Apprentice scholar
- [Salvia the Sage](/cast/the_emerald_lights.qmd#salvia-the-sage) (he/him)
    - One of the three leaders of the “Emerald Lights”

## Fabriknock (Fa-bree-knock)


- [The Violet Knight](/cast/the_emerald_knights.qmd#the-violet-knight)
    - Ruler
- [Mr .Something](/cast/fabriknock_vassals.qmd#mr.-something) (he/him)
    - Head guard
- [Turnebucke something](/cast/fabriknock_vassals.qmd#turnebucke-something) (he/him)
    - Guard and son of Mr. Something
- [The Forge Knight](/cast/the_emerald_knights.qmd#the-forge-knight)
    - Was [Crabbe](/cast/the_emerald_lights.qmd#crabbe) (they/them)
    - Local leader of the Emerald Lights

## Inis Ocular (Inn-ish Awk-you-lar)

- [The Shield Knight](/cast/other_holding_knights.qmd#the-shield-knight) (she/her) 2-8
    - Ex-ruler
    - Deceased
- [Mentha the Mint](/cast/the_emerald_lights.qmd#mentha-the-mint) (they/them)
    - One of the three leaders of the “Emerald Lights”
    - Ousted

## Misc

- [The Cosmic Knight](/cast/the_emerald_knights.qmd#the-cosmic-knight)
    - Was [Mentha the Mint](/cast/the_emerald_lights.qmd#mentha-the-mint)
- [The Reliquary Knights](/cast/the_emerald_knights.qmd#the-reliquary-knight)
- [The Leaf Knight](/cast/other_holding_knights.qmd#the-leaf-knight) (she/her) 6-3
    - Ex-ruler of Fabirrnock
    - Now a player
